name: Release

on:
  push:
    tags:
      - v*

jobs:
  PyPIBuild:
    if: ${{ github.repository == 'resurfemg/resurfemg' }}
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
        # Unfortunately, wheel will try to do setup.py install to
        # build a wheel... and we need this stuff to be able to build
        # for CPython.

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: python3.9 -m venv .venv
      - run: .venv/bin/python -m pip install build wheel twine
      - run: .venv/bin/python -m build
      # - run: .venv/bin/python setup.py bdist_egg
      - run: >-
          TWINE_USERNAME=__token__
          TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }}
          .venv/bin/python -m twine upload --skip-existing ./dist/*.whl
      - uses: actions/upload-artifact@v4
        with:
          name: pypi-build
          path: dist/*

  PublishArtifacts:
    runs-on: ubuntu-latest
    needs: [PyPIBuild]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUBTOKEN }}"
          prerelease: false
          files: |
            ./dist/*/linux-64/resurfemg-*.tar.bz2
            ./dist/*/osx-64/resurfemg-*.tar.bz2
            ./dist/*/win-64/resurfemg-*.tar.bz2
            ./dist/pypi-build/*.whl
