name: Deployability
on:
    pull_request:
        branches:
            - 'main'
jobs:
  Test-Sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: python3 -m venv .venv
    - run: .venv/bin/python -m pip install wheel sphinx setuptools
    - run: .venv/bin/python -m pip install -e .[docs]
    - run: .venv/bin/python setup.py apidoc
    - run: .venv/bin/python setup.py build_sphinx -W